### ISSUE TITLE
have this problem been solved? 

### ISSUE THREAD

**Issue by limng06** [jvdmr/spring-boot-war-example#1] opened 2018-11-28 09:00 UTC
> Set<BeanDefinition> beanSet = getScanner().findCandidateComponents(BASE_PACKAGE);

i have the same problem, when my program run with java -jar  XXX.war command.

please let me know if you have solve this problem

**Comment by jvdmr** [comment] 2018-11-29 09:03
This was a minimal testcase to help identify and resolve spring-projects/spring-boot#7949

As I understand it, this issue was fixed by the Spring Boot team before the release of 1.5.0. Indeed, if I adjust the spring boot version in the pom.xml to 1.5.0.RELEASE, everything works as intended.

I'll add a Readme to clarify this.

**Closed by jvdmr** 2018-11-29 09:03 UTC
